# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Euskovid-19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid19

  pod 'SwiftyJSON', '~> 4.0'
  
end
